name: Roast My PR
on:
  pull_request:
    # Run this action whenever a pull request is created or updated
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AlexanderOtavka/roast-my-pr@v1.1.1
    - name: Roast My PR
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
